name: Website/Astro – Build and Push

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    DOCKER_BUILDKIT: 1
    COMPOSE_DOCKER_CLI_BUILD: 1

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Cache turbo build setup
              uses: actions/cache@v4
              with:
                  path: .turbo
                  key: ${{ runner.os }}-turbo-${{ github.sha }}
                  restore-keys: ${{ runner.os }}-turbo-cc-web

            - name: Install Railpack CLI
              run: |
                  curl -sSL https://railpack.com/install.sh | sh
                  # or download binary from GitHub releases

            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                  images: ghcr.io/collective-change-org/website

            - name: Set Docker tag
              id: date
              run: echo "DATE_STAMP=$(date +%s)" > "$GITHUB_ENV"

            - name: Build and push Docker images
              uses: iloveitaly/github-action-nixpacks@main
              with:
                  push: true
                  tags: |
                      ghcr.io/collective-change-org/website:custom-${{ env.DATE_STAMP }}
                      ghcr.io/collective-change-org/website:latest
                  env: NIXPACKS_NODE_VERSION=20,CMS_URL=${{ secrets.CMS_URL }},PAYLOAD_EMAIL=${{ secrets.PAYLOAD_EMAIL }},PAYLOAD_PASSWORD=${{ secrets.PAYLOAD_PASSWORD }}

            - name: Trigger Dokploy Deployment
              run: |
                  curl -X 'POST' \
                  '${{ secrets.DOKPLOY_URL }}/api/trpc/application.deploy' \
                  -H 'accept: application/json' \
                  -H 'x-api-key: ${{ secrets.DOKPLOY_AUTH_TOKEN }}' \
                  -H 'Content-Type: application/json' \
                  -d '{
                      "json":{
                          "applicationId": "${{ secrets.DOKPLOY_WEBSITE_APPLICATION_ID }}"
                      }
                  }'
