name: Website/Astro – Build and Push

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    DOCKER_BUILDKIT: 1
    COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Cache turbo build setup
              uses: actions/cache@v4
              with:
                  path: .turbo
                  key: ${{ runner.os }}-turbo-${{ github.sha }}
                  restore-keys: ${{ runner.os }}-turbo-cc-web

            - name: Install Railpack CLI
              run: |
                  curl -sSL https://railpack.com/install.sh | sh
                  # or download binary from GitHub releases

            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                  images: ghcr.io/collective-change-org/website

            - name: Set Docker tag
              id: date
              run: echo "DATE_STAMP=$(date +%s)" > "$GITHUB_ENV"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  install: true
                  driver-opts: image=moby/buildkit:latest

            # - name: Build and push Docker image
            #   uses: docker/build-push-action@v6
            #   with:
            #       # context: apps/website
            #       file: apps/website/Dockerfile
            #       push: true
            #       build-args: |
            #           PAYLOAD_EMAIL=${{ secrets.PAYLOAD_EMAIL }}
            #           PAYLOAD_PASSWORD=${{ secrets.PAYLOAD_PASSWORD }}
            #           CMS_URL=${{ secrets.CMS_URL }}
            #       tags: |
            #           ghcr.io/collective-change-org/website:custom-${{ env.DATE_STAMP }}
            #           ghcr.io/collective-change-org/website:latest
            #       cache-from: type=gha
            #       cache-to: type=gha,mode=max

            - name: Run Railpack prepare
              run: |
                  railpack prepare . \
                    --plan-out railpack-plan.json \
                    --info-out railpack-info.json \
                    --env PAYLOAD_EMAIL=${{ secrets.PAYLOAD_EMAIL }} \
                    --env PAYLOAD_PASSWORD=${{ secrets.PAYLOAD_PASSWORD }} \
                    --env CMS_URL=${{ secrets.CMS_URL }}

            # Log out current directory content
            - name: Log out current directory content
              run: |
                  pwd
                  ls -l

            # cat railpack-plan.json
            - name: Log out railpack-plan.json
              run: |
                  cat railpack-plan.json

            - name: Build Docker image
              run: |
                  docker buildx build \
                  --build-arg BUILDKIT_SYNTAX="ghcr.io/railwayapp/railpack-frontend" \
                  --secret id=PAYLOAD_EMAIL,env=PAYLOAD_EMAIL \
                  --secret id=PAYLOAD_PASSWORD,env=PAYLOAD_PASSWORD \
                  --secret id=CMS_URL,env=CMS_URL \
                  -f ./railpack-plan.json \
                  --tag ghcr.io/collective-change-org/website:${{ github.sha }} \
                  --tag ghcr.io/collective-change-org/website:latest \
                  --push \
                  /home/runner/work/website/website

            - name: Trigger Dokploy Deployment
              run: |
                  curl -X 'POST' \
                  '${{ secrets.DOKPLOY_URL }}/api/trpc/application.deploy' \
                  -H 'accept: application/json' \
                  -H 'x-api-key: ${{ secrets.DOKPLOY_AUTH_TOKEN }}' \
                  -H 'Content-Type: application/json' \
                  -d '{
                      "json":{
                          "applicationId": "${{ secrets.DOKPLOY_WEBSITE_APPLICATION_ID }}"
                      }
                  }'
