name: Website/Astro – Build and Push

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                  images: ghcr.io/collective-change-org/website

            # - name: Set Docker tag
            #   id: date
            #   run: echo "DATE_STAMP=$(date +%s)" > "$GITHUB_ENV"

            # - name: Build and push Docker images
            #   uses: iloveitaly/github-action-nixpacks@main
            #   with:
            #       context: apps/website
            #       push: true
            #       tags: |
            #           ghcr.io/collective-change-org/website:custom-${{ env.DATE_STAMP }}
            #           ghcr.io/collective-change-org/website:latest

            - name: Build and push Docker image
              uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
              with:
                  # context: apps/website
                  file: apps/website/Dockerfile
                  push: true
                  build-args: |
                      PAYLOAD_EMAIL=${{ secrets.PAYLOAD_EMAIL }}
                      PAYLOAD_PASSWORD=${{ secrets.PAYLOAD_PASSWORD }}
                      CMS_URL=${{ secrets.CMS_URL }}
                  tags: |
                      ghcr.io/collective-change-org/website:custom-${{ env.DATE_STAMP }}
                      ghcr.io/collective-change-org/website:latest

            # - name: Build and push Docker image
            #   uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
            #   with:
            #       context: .
            #       file: apps/website/Dockerfile
            #       push: true
            #       tags: |
            #           ${{ steps.meta.outputs.tags }}
            #           ghcr.io/collective-change-org/website:latest
            #       # Commit Hash and Latest as tags

            # - name: Dokploy Deployment
            #   uses: benbristow/dokploy-deploy-action@0.0.1
            #   with:
            #       auth_token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
            #       application_id: ${{ secrets.DOKPLOY_APPLICATION_ID }}
            #       dokploy_url: ${{ secrets.DOKPLOY_URL }}
